#!/bin/bash -l

#SBATCH --partition=gpu
#SBATCH --nodes=1 --ntasks=24
#SBATCH --mem=600G --gres=gpu:1 --time=1-0:00
#SBATCH --job-name=ROBOKOPKG_baseline_calculate_attribute_embedding
#SBATCH --output=/home/jchung/ROBOKOP/git/xDTD_training_pipeline/log_folder/cal_20240620.out
#SBATCH --mail-user=jchung@renci.org
#SBATCH --mail-type=ALL

export LD_LIBRARY_PATH=/home/jchung/miniconda3/lib:$LD_LIBRARY_PATH
cd /home/jchung/ROBOKOP/git/xDTD_training_pipeline/scripts

/home/jchung/miniconda3/envs/main_env/bin/python -u calculate_attribute_embedding.py --batch_size 100 --node_info ../data/rkg_embedding_input/filtered_graph_nodes_info.txt
