#!/bin/bash -l

#SBATCH --partition=gpu
#SBATCH --nodes=1 --ntasks=24
#SBATCH --mem=660G --gres=gpu:1 --time=10-0:00
#SBATCH --job-name=ROBOKOPKG_baseline_random_forest
#SBATCH --output=/home/jchung/ROBOKOP/git/xDTD_training_pipeline/log_folder/RKG_baseline_graphsage_RF_train_%j.out
#SBATCH --mail-user=jchung@renci.org
#SBATCH --mail-type=ALL

cd /home/jchung/ROBOKOP/git/xDTD_training_pipeline

/home/jchung/miniconda3/envs/main_env/bin/python -u scripts/run_RF_model_3class.py 
