#!/bin/bash -l

#SBATCH --partition=gpu
#SBATCH --nodes=1 --ntasks=24
#SBATCH --mem=660G --gres=gpu:1 --time=10-0:00
#SBATCH --job-name=ROBOKOPKG_baseline_graphsage_result_transform
#SBATCH --output=/home/jchung/ROBOKOP/git/xDTD_training_pipeline/log_folder/RKG_baseline_graphsage_result_transform.out
#SBATCH --mail-user=jchung@renci.org
#SBATCH --mail-type=ALL

cd /home/jchung/ROBOKOP/git/xDTD_training_pipeline

/home/jchung/miniconda3/envs/main_env/bin/python -u scripts/transform_format.py --input /home/jchung/ROBOKOP/git/xDTD_training_pipeline/unsup-graphsage_input/graphsage_mean_big_0.001000
